In [4]:
import pandas as pd
from pandas import read_parquet
df = read_parquet(r"C:\Users\lefte\Desktop\GitHub Projects\Thesis_project\data\processed\final_training_dataset_with_weather.parquet")
df.head()

,rideable_type,started_at,member_casual,city,trip_duration,same_station,day_of_week,month,is_weekend,part_of_day,...,haversine_distance_km,bearing_sin,bearing_cos,hour,temperature_c,precipitation_mm,wind_speed_kph,snow_mm,rain_flag,snow_flag
0,classic_bike,2025-01-18 15:59:26.296,casual,chicago,63.633333,0,5,1,1,midday,...,11.370089,0.085612,-0.996329,15,-1.1,0.0,33.5,0,0,0
1,classic_bike,2025-01-04 15:50:40.398,casual,chicago,8.350000,0,5,1,1,midday,...,1.582292,0.107283,0.994228,15,-9.4,0.0,18.4,0,0,0
2,classic_bike,2025-01-05 14:07:30.549,casual,chicago,7.366667,0,6,1,1,midday,...,1.132614,-0.980667,-0.195685,14,-7.8,0.0,5.4,0,0,0
3,classic_bike,2025-01-04 15:34:02.555,casual,chicago,1.433333,1,5,1,1,midday,...,0.000000,0.000000,1.000000,15,-9.4,0.0,18.4,0,0,0
4,classic_bike,2025-01-26 15:02:25.915,casual,chicago,1.466667,1,6,1,1,midday,...,0.000000,0.000000,1.000000,15,-6.7,0.0,16.6,0,0,0

In [5]:
df.columns

Index(['rideable_type', 'started_at', 'member_casual', 'city', 'trip_duration',
       'same_station', 'day_of_week', 'month', 'is_weekend', 'part_of_day',
       'hour_sin', 'hour_cos', 'haversine_distance_km', 'bearing_sin',
       'bearing_cos', 'hour', 'temperature_c', 'precipitation_mm',
       'wind_speed_kph', 'snow_mm', 'rain_flag', 'snow_flag'],
      dtype='object')

In [12]:
df2 = read_parquet(r"C:\Users\lefte\Desktop\GitHub Projects\Thesis_project\data\processed\london_featured_with_weather.parquet")
df2.head()

,rideable_type,started_at,member_casual,city,trip_duration,same_station,hour,day_of_week,month,is_weekend,...,haversine_distance_km,bearing,bearing_sin,bearing_cos,temperature_c,precipitation_mm,wind_speed_kph,snow_mm,rain_flag,snow_flag
0,classic_bike,2025-01-14 23:59:00,unknown,london,14.507800,0,23,1,1,0,...,2.843154,104.199923,0.969446,-0.245306,7.1,0.0,9.3,0,0,0
1,classic_bike,2025-01-14 23:59:00,unknown,london,5.119683,0,23,1,1,0,...,0.452576,144.340194,0.582971,-0.812493,7.1,0.0,9.3,0,0,0
2,classic_bike,2025-01-14 23:59:00,unknown,london,10.679250,0,23,1,1,0,...,1.528633,340.134202,-0.339818,0.940491,7.1,0.0,9.3,0,0,0
3,classic_bike,2025-01-14 23:59:00,unknown,london,10.709133,0,23,1,1,0,...,1.781185,239.703790,-0.863429,-0.504471,7.1,0.0,9.3,0,0,0
4,electric_bike,2025-01-14 23:58:00,unknown,london,15.736417,0,23,1,1,0,...,9.349490,78.815942,0.981009,0.193961,7.1,0.0,9.3,0,0,0

In [6]:
df.columns

Index(['rideable_type', 'started_at', 'member_casual', 'city', 'trip_duration',
       'same_station', 'day_of_week', 'month', 'is_weekend', 'part_of_day',
       'hour_sin', 'hour_cos', 'haversine_distance_km', 'bearing_sin',
       'bearing_cos', 'hour', 'temperature_c', 'precipitation_mm',
       'wind_speed_kph', 'snow_mm', 'rain_flag', 'snow_flag'],
      dtype='object')

In [13]:
df2.columns

Index(['rideable_type', 'started_at', 'member_casual', 'city', 'trip_duration',
       'same_station', 'hour', 'day_of_week', 'month', 'is_weekend',
       'part_of_day', 'hour_sin', 'hour_cos', 'delta_lat', 'delta_lng',
       'haversine_distance_km', 'bearing', 'bearing_sin', 'bearing_cos',
       'temperature_c', 'precipitation_mm', 'wind_speed_kph', 'snow_mm',
       'rain_flag', 'snow_flag'],
      dtype='object')